[firebase]
type = "service_account"
project_id = "marketing-automation-3098a"
private_key_id = "136e5b1fb29ee82ce7f32415dd3ad040e8faf402"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwBlEpQ33ts4/f
Tor5MN2YzobJKlx6zs3anfPhoHM8Dc9v83PCZwHjsAQhO5+Vjm2wSxdKKUeOiG0s
OGrXFIt8e/I8gSS6KDcmN1fQ9qClJeu1mGuYbImb7QNbbLKQ+ouAJ0CWNvdHEwHg
iF0RfIC7F0hsPErXuSOR7NQDOJRZEsnpGjLBtrNOj4ntztb+bvRBm+ub2xuOmU0V
m35vRcVjysla8zolSH26kggMcBfN6mVvavkbtGG9ywS77P0sP44na5PBJ9E2JVJK
EbQlgvnFtzp2otYyqlz1iEdjHR52hu9qQmBfam/PwSgHfqpJuXiR/gsH/EWDK7IO
G0fHazttAgMBAAECggEAATIlyoM6H4uNAm4g7RT7KG7cxRCb3Ly7cs0Ia2PA7KtG
WcMcaflzrpWTTZt/V8+GKMC12Yviv9Hm9fozJZ9u3CtmZ6lT88zSpRiSqOmICV8y
1QLCVmCEZdIMKAqawvfkyzvZCTw53VqAdINQqI4BPOQpWozlUEZiersSbKwte9Zt
NDf75yjajorFMFREcFNA1jMIewuIhOd9LaR1gWsMyIiM3rFO3R4d27tOurZYmqV4
5VB071hnhSiXn8oZnwDoInAQfuMFeMEEDN/7hyd89NNVTf2CF4HKzo3G0yGs5Eq/
vHuEthsxVZRGM94HrAXgsBFxmlHpD4LcD2yJV0Iv6QKBgQDdHPgJ+QgAsp6YAlBq
MeMPNLfVKJheR1MCavl/PHS/CQNk/dN9wEfUT3558KTSknoQr4kX+RIs9ETjIurv
7+cC3vseaBUA8kp0OR7P/vtWJM/8x0D7KAiAGdSmLVQevZp2aaM7KKg4DV/0nHLk
nmLJq0pXeafLLaR2IhZFiMLdSQKBgQDLzCtJ57ntvvgkmk5n29DwuHJuFhwJWj5W
qkQxk/PWcQKrFnIQ9MDa861g9oWpkRBJ8rUIfWz0yXWVFqavUHQQCzxRuoThWwES
KacyRCGFQ05e/YpXzHWyr/T1ECAXdUkGTxnJlIguZ1SIkwP81baUe/i95bdLqfL/
Y2lUlOKhBQKBgQCl/axbWD9gvrb+aKZTwpWxgaML+4i/Jg4z/3jDwu/lxe9tbnvJ
qIKD6RWKl1Q03E+UnSJvA8VYSBw646i5bUDgT+L3Ba3W4w1vyL3P6ZxnJAWbvz2S
DpCrEjkoc1j2JuKBSHaI39HBGpFRge1ioWCKAvQxTRvhFKelI5vSoYOgOQKBgGZr
bTXvJxm8Z6i9g7neVtsjVx7MLbrlh362gx8HY/vZP6YL2bd7yZA/9lpMik/1f2Iq
f6CMqD09IcKTZ6GjpTCK9P1951n6Cke+dzBj3RTEBpbmhKgrMNtkYo7mU7p2TwTE
rAkKhIYNmAYrHE3seZ2V0CRfVgbImj6PD1hamqqhAoGBALmz96aYJUAFsjYqeygV
XwyIrwqkk8EeKAbJ/g7vX4622wh4xLdmIX1pYe2rI9uRf7QjM6sJx0hh/kwDpVTb
idDB8LoPw244pJ1tqet1TyQ717YugM+hnOCAcq+8vWQnsMxuMQo54Ss231hRpRey
WnCaV+ChrJMZcaBG0s/ArsEb
-----END PRIVATE KEY-----
'''
client_email = "firebase-adminsdk-pttoo@marketing-automation-3098a.iam.gserviceaccount.com"
client_id = "109229821960766497206"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-pttoo%40marketing-automation-3098a.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
